baseURL = "https://rex-makusia.github.io/devpollinate/"
languageCode = "en-us"
title = "Dev Pollinate"
theme = "PaperMod"

[params]
  author = "Rex Makusia"
  description = "My DevOps Portfolio showcasing my projects, blogs, and open-source contributions."
  github = "https://github.com/your-username"
  linkedin = "https://linkedin.com/in/your-profile"

  # Ensure only blog posts appear on the homepage
  mainSections = ["blog"]  

  [params.assets]
    disableFingerprinting = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4