baseURL = "https://rex-makusia.github.io/devpollinate/"
languageCode = "en-us"
title = "Dev Pollinate"
theme = "PaperMod"

[params]
  author = "Rex Makusia"
  description = "My DevOps Portfolio showcasing my projects, blogs, and open-source contributions."
  github = "https://github.com/rex-makusia"
  linkedin = "https://www.linkedin.com/in/rex-makusia-00333994/"

[params.assets]
  disableFingerprinting = true

# Specify that blog posts should appear on the homepage
mainSections = ["blog"]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3